language: python
python:
  - "3.5"

sudo: false

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111

install:
  - pip install coveralls tox virtualenv

script:
  - tox

after_script:
  - coveralls
