# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-26 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_grant_pkce_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='enable_pkce',
            field=models.BooleanField(default=False),
        ),
    ]
